# Generated by Django 5.2.5 on 2025-08-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='roommates_found',
        ),
    ]
