# Generated by Django 5.2.5 on 2025-08-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='roommates_found',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='roommates_needed',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
