# Generated by Django 5.2.5 on 2025-08-18 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_roommates_found_listing_roommates_needed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_roommates',
            field=models.ManyToManyField(blank=True, related_name='current_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
