# Generated by Django 5.2.5 on 2025-08-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_current_roommates'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
