# Generated by Django 5.2.5 on 2025-08-19 15:24

import cloudinary.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Seeker', 'Seeker'), ('Lister', 'Lister')], default='Seeker', max_length=10)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar')),
                ('cleanliness', models.IntegerField(default=3)),
                ('sleep_schedule', models.CharField(default='Flexible', max_length=20)),
                ('noise_level', models.IntegerField(default=3)),
                ('guest_frequency', models.CharField(default='Occasionally', max_length=20)),
                ('social_level', models.CharField(default='Friendly but independent', max_length=30)),
                ('smoking', models.CharField(default='Non-Smoker', max_length=20)),
                ('has_pets', models.BooleanField(default=False)),
                ('gender_preference', models.CharField(default='No Preference', max_length=20)),
                ('work_schedule', models.CharField(default='9-to-5', max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('mbti_type', models.CharField(blank=True, max_length=4, null=True)),
                ('budget', models.PositiveIntegerField(default=1000)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorited_by', to='listings.listing')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
