# Generated by Django 5.2.5 on 2025-08-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cleanliness',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='noise_level',
            field=models.IntegerField(default=3),
        ),
    ]
